#!/usr/bin/env python3
"""TASK 1 addendum -- exact tail probabilities for the injection control.

Where does the ACTUAL stub injection (4 helpers, max LOO impact +0.0185, at
n = 37 on the base-asset build -- the configuration in which the paper's
contaminated panel was analysed) sit inside the distribution generated by
injecting three ARBITRARY rows into the same clean 34-asset corpus?
"""
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
import common as C                                             # noqa: E402
from t01_stub_leverage import arm, make_injected               # noqa: E402

OUTF = Path(__file__).parent / "results_t01b_injection_tails.json"
STUBS = ['AXS', 'SUSHI', 'YFI']
NDRAW = 400


def main():
    rng = np.random.default_rng(4242)
    cl_dirty, sym_dirty = C.load_claims(clean=False)
    cl_clean, sym_clean = C.load_claims(clean=True)
    fac, fsym = C.load_factors()
    out = {}

    for build in ['base', 'usd_close']:
        z, ssym, _ = C.build_stats_matrix(build)
        common_dirty = sorted(set(sym_dirty) & set(ssym) & set(fsym))
        common_clean = sorted(set(sym_clean) & set(ssym) & set(fsym))
        L = sorted(set(common_dirty) & set(common_clean))
        B = cl_clean[[sym_clean.index(s) for s in L]]
        stub_prof = np.array([cl_dirty[sym_dirty.index(s)] for s in STUBS])

        obs = arm(*make_injected(B, L, STUBS, stub_prof), z, ssym, fac, fsym,
                  L + STUBS, f'{build}: clean34 + real stubs')

        arms = {}
        for nm in ['dirichlet_flat', 'resample_real', 'stub_shuffled']:
            H, M = [], []
            for _ in range(NDRAW):
                if nm == 'dirichlet_flat':
                    prof = rng.dirichlet(np.ones(10), size=3)
                elif nm == 'resample_real':
                    prof = B[rng.choice(len(B), size=3, replace=False)]
                else:
                    prof = np.array([p[rng.permutation(10)] for p in stub_prof])
                r = arm(*make_injected(B, L, STUBS, prof), z, ssym, fac, fsym,
                        L + STUBS, '', verbose=False)
                H.append(r['n_helpers']); M.append(r['max_impact'])
            H, M = np.array(H), np.array(M)
            arms[nm] = {
                'n_draws': NDRAW,
                'P_nhelpers_ge_observed': float((H >= obs['n_helpers']).mean()),
                'P_maximpact_ge_observed': float((M >= obs['max_impact']).mean()),
                'E_nhelpers': float(H.mean()),
                'P_nhelpers_ge1': float((H >= 1).mean()),
                'P_nhelpers_ge2': float((H >= 2).mean()),
                'P_nhelpers_ge3': float((H >= 3).mean()),
                'P_nhelpers_ge4': float((H >= 4).mean()),
                'maximpact_mean': float(M.mean()),
                'maximpact_q50': float(np.percentile(M, 50)),
                'maximpact_q90': float(np.percentile(M, 90)),
                'maximpact_q95': float(np.percentile(M, 95)),
                'maximpact_max': float(M.max()),
            }
            a = arms[nm]
            print(f"  [{build:9s} {nm:15s}] P(#helpers >= {obs['n_helpers']}) = "
                  f"{a['P_nhelpers_ge_observed']:.4f}   "
                  f"P(max impact >= {obs['max_impact']:+.4f}) = "
                  f"{a['P_maximpact_ge_observed']:.4f}   "
                  f"P(>=1)={a['P_nhelpers_ge1']:.3f} P(>=2)={a['P_nhelpers_ge2']:.3f} "
                  f"P(>=3)={a['P_nhelpers_ge3']:.3f} P(>=4)={a['P_nhelpers_ge4']:.3f}")
        out[build] = {'observed': obs, 'controls': arms}

    json.dump(out, open(OUTF, 'w'), indent=2)
    print(f"wrote {OUTF}")


if __name__ == '__main__':
    main()
